DATASET:
  version: "V1"
  base_dir: "/mnt/disk/dataset/sentinel-ai-processor"
  bands : ["B02", "B03", "B04"]

ENDPOINTS:
  url: "ttps://eodata.dataspace.copernicus.eu"
  stac: "https://stac.dataspace.copernicus.eu/v1/"
  bucket_name: "eodata"

MODEL:
  model_name: "Unet"
  encoder_name: "resnet34"
  in_channel: 3
  out_channels: 3

TRAINING:
    seed: 42
    resize : 1024
    learning_rate: 1e-3
    batch_size: 16
    n_epoch: 5
    num_workers : 8



